In [1]:
import numpy as np

In [5]:
x = [1,2,3,4,5]
y = [5,4,3,2,1]

cov_1 = np.array([x,y])

In [8]:
cov_1

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [7]:
np.cov(cov_1)

array([[ 2.5, -2.5],
       [-2.5,  2.5]])

In [9]:
np.cov(cov_1)[0][1]

-2.5

In [10]:
x = [1, 2, 3, 4, 5]
y = [5, 4, 3, 2, 1]

np.cov(x,y)

array([[ 2.5, -2.5],
       [-2.5,  2.5]])